@ReceiptCalculator.Api_HostAddress = http://localhost:5188

GET {{ReceiptCalculator.Api_HostAddress}}/api/health
Accept: application/json

###

POST {{ReceiptCalculator.Api_HostAddress}}/api/receipt/analyze
Content-Type: application/json

{
	"imageBase64": "",
	"currency": "MYR"
}

###
