[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.client"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
ASPNETCORE_ENVIRONMENT = "Production"
